---
output:
  bookdown::pdf_document2:
    toc : no
    keep_tex: no
    number_sections: yes
---

# Conclusions

- *Climate change mitigation will have a large impact on biomass and MCP loss in the area.* On the aggregated level, climate change mitigation plays a pivotal role in influencing biomass and MCP loss within the study area with SSP 126 resulting in less abundance (and MCP) loss in all management Scenarios (Figure \@ref(fig:linetrend)). Interestingly, by 2050 abundance is less impacted by climate change under SSP 585 than 126, but such pattern reverts towards the end of the century. This is probably explained by the abundance increase of Perch-likes in the study area under SSP 585 (Figure \@ref(fig:commercialmap)). However, upon initial assessment, such increase does not seem to be influenced by the Cocos or AMM protected areas, nor the management scenarios, but rather the overarching effects of climate change.

- *On aggregate, a combination of protected area, limited IUU fishing and sustainable resource management (i.e a conservation inclined scenario) will result in less losses in biomass by the middle of the 21st century.* This strategy represents a holistic approach to marine resource management. By prioritizing ecosystem health and sustainable fisheries, the social-ecological system will be better prepared to address the impacts of climate change by the middle of the 21st century. While these actions might not be enough to fully stop the impacts of climate change, according to our results a more conservation-inclined scenario will still result in less impacts than other scenarios. Moreover, a more "conservation-inclined" scenario does not necessary mean less fishing. While in this scenario fishers loose complete access to fishing in the closed area, having the cocos MPA working as a 100% no-take MPA does not influence the catch potential of the outside region. Finally, according to out results, this scenario still results in less overall impacts to MCP than the other scenarios. 

- *On a commercial-group level, both sharks & rays and tunas & billfishes are expected to decrease in abundance (and MCP), and perch-likes are expected to decrease in abundance but not MCP.* The commercial-group level analysis provided insights into the expected trends for key marine species groups at a slightly less uncertain way than looking directly to each species (Figure \@ref(fig:scentrendcommercial)). The overall decrease in abundance for sharks & rays and tunas & billfishes is somehow expected as the Cocos MPA and extended AMM area might not be large enough to properly protect these highly migratory species. Interestingly, spatially speaking, the model suggests that the Cocos area will retain some sharks and rays biomass under both SSPs for Scenario one and under SSP 585 for scenario Two. While this sounds like a promising result, we caution its interpenetration given the small number of protected grid-cells in the study area, especially because the increase is highly concentrated on an even smaller number of grid-cells (Figure \@ref(fig:scenariodeltaboxcommercial)). On the other hand, the specific case of Perch-likes species suggests a more complex relationship where abundance and MCP do not decline in tandem. While this can also be influenced by the scale mismatch previously mentioned, it warrants further research to understand why this pattern and address the underlying factors creating this effect.

- *A holistic approach where climate change is mitigated, marine biodiversity protected and fisheries well managed are is the best chance to increase resilience to climate change.* Indeed, mitigating greenhouse gases to follow SSP 126 and keep temperatures under the $1.5^o$C will be essential to protect ocean biodiversity and keep fisheries sustainable [@Cheung.2016]. Forevermore, while MPAs and fisheries management strategies play essential roles in localized conservation efforts, their immediate impact on the broader environmental shifts observed may be limited [@PalaciosAbrantes.2023c8m]. This is especially true for climate change. For example, having an MPA will not stop species for shifting out of it as temperatures in the region rise [@FredstonHermann.2018] (although it will also not stop species coming in), and fishing at MSY will not necessarily address reductions in biomass due to climate change [@Cheung.2022bw]. It is therefore crucial to recognize and analyse the complex interaction of social-ecological systems and climate change to develop comprehensive strategies for addressing ongoing environmental challenges effectively.

# References